[workspace]
resolver = "2"
members = ["crates/*", "py-kola", "bindings/napi-kola"]
default-members = ["crates/*"]

[workspace.package]
version = "2.5.1"
authors = ["Jo Shinonome <jo.shinonome@gmail.com>"]
edition = "2021"
repository = "https://github.com/jshinonome/kola"
license = "BSD-3-Clause"
description = "a Python Polars interface to q"

[profile.dev]
opt-level = 1

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "unwind"

[profile.node-release]
inherits = "release"
opt-level = 3
panic = "unwind"

[workspace.dependencies.polars-buffer]
default-features = false
version = "0.55.2"

[workspace.dependencies.polars-arrow]
default-features = false
version = "0.55.2"

[workspace.dependencies.polars]
version = "0.55.2"
