# https://taskfile.dev

version: "3"

vars:
  VERSION:
    sh: grep "version" Cargo.toml | head -1 | cut -d'"' -f 2

tasks:
  default:
    cmds:
      - cargo update
    silent: true

  venv:
    cmds:
      - uv venv --python 3.12
      - uv pip install pip
      - uv pip install -r py-kola/requirements.txt

  test:
    cmds:
      - cargo test

  install-python:
    deps:
      - release-python
    cmds:
      - uv pip install dist/*

  test-python:
    dir: py-kola
    cmds:
      - pytest -vv

  tag:
    cmds:
      - git tag {{.VERSION}} && git push origin tag {{.VERSION}}

  release-python:
    cmds:
      - rm -rf dist
      - maturin build --release --out dist -i python3.12 --manifest-path py-kola/Cargo.toml
