# https://taskfile.dev

version: "3"

vars:
  VERSION:
    sh: grep "version" Cargo.toml | head -1 | cut -d'"' -f 2

tasks:
  default:
    cmds:
      - cargo update
    silent: true

  venv:
    cmds:
      - uv venv --python 3.12
      - uv pip install pip
      - uv pip install -r py-kola/requirements.txt

  test:
    cmds:
      - cargo test

  install-python:
    deps:
      - release-python
    cmds:
      - uv pip install target/wheels/*

  test-python:
    dir: py-kola
    cmds:
      - pytest -vv

  tag:
    cmds:
      - git tag {{.VERSION}} && git push origin tag {{.VERSION}}

  podman-release:
    cmds:
      - podman run -it --rm -v $PWD:/build:Z -v $HOME/.cargo:$HOME/.cargo:Z manylinux2014 /bin/bash -i -c "task release-python"

  podman-build:
    cmds:
      - podman run -it --rm -v $PWD:/build:Z -v $HOME/.cargo:$HOME/.cargo:Z manylinux2014 /bin/bash -i -c "task build-python"

  build-python:
    cmds:
      - |
        ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/opensslconf.h
        ln -s /usr/include/x86_64-linux-gnu/openssl/configuration.h /usr/include/openssl/configuration.h
        export OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu
        export OPENSSL_INCLUDE_DIR=/usr/include
        python3.12 -m venv .venv
        pip3.12 install -r py-kola/requirements.txt
        export RUSTFLAGS="-C target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+avx2,+fma,+bmi1,+bmi2,+lzcnt"
        maturin develop --strip --manifest-path py-kola/Cargo.toml

  release-python:
    cmds:
      - |
        ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/opensslconf.h
        ln -s /usr/include/x86_64-linux-gnu/openssl/configuration.h /usr/include/openssl/configuration.h
        export OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu
        export OPENSSL_INCLUDE_DIR=/usr/include
        pip3.12 install -r py-kola/requirements.txt
        export RUSTFLAGS="-C target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+avx2,+fma,+bmi1,+bmi2,+lzcnt"
        maturin build --release --out dist -i python3.12 --manifest-path py-kola/Cargo.toml
