[package]
name = "py-kola"
version.workspace = true
edition = "2021"

[lib]
name = "kola"
crate-type = ["cdylib"]

[dependencies]
kola = { path = "../crates/kola" }
pyo3 = { version = "0.29.1", features = ["chrono", "abi3-py310"] }
thiserror = "2.0.18"
pyo3-polars = { version = "0.28.0", features = [
  "dtype-categorical",
  "dtype-array",
  "dtype-full",
] }
chrono = "0.4.45"
indexmap = "2.14.0"

[dependencies.polars]
workspace = true
