from enum import Enum


class Operator(Enum):
    """q primitives (IPC types 101 and 102); values are their q names.

    PLUS represents unary +:; BINARY_PLUS represents binary +.
    Generic null is represented by None, separately from PROJECTION_NULL.
    """

    PLUS = "+:"
    MINUS = "-:"
    MULTIPLY = "*:"
    DIVIDE = "%:"
    AND = "&:"
    OR = "|:"
    CARET = "^:"
    EQUAL = "=:"
    LESS = "<:"
    GREATER = ">:"
    DOLLAR = "$:"
    COMMA = ",:"
    HASH = "#:"
    UNDERSCORE = "_:"
    TILDE = "~:"
    BANG = "!:"
    QUESTION = "?:"
    AT = "@:"
    DOT = ".:"
    ZERO_COLON = "0::"
    ONE_COLON = "1::"
    TWO_COLON = "2::"
    AVG = "avg"
    LAST = "last"
    SUM = "sum"
    PRD = "prd"
    MIN = "min"
    MAX = "max"
    EXIT = "exit"
    GETENV = "getenv"
    ABS = "abs"
    SQRT = "sqrt"
    LOG = "log"
    EXP = "exp"
    SIN = "sin"
    ASIN = "asin"
    COS = "cos"
    ACOS = "acos"
    TAN = "tan"
    ATAN = "atan"
    ENLIST = "enlist"
    VAR = "var"
    DEV = "dev"
    HOPEN = "hopen"
    PROJECTION_NULL = "::"

    # K102 binary operators
    ASSIGN = ":"
    BINARY_PLUS = "+"
    BINARY_MINUS = "-"
    BINARY_MULTIPLY = "*"
    BINARY_DIVIDE = "%"
    BINARY_AND = "&"
    BINARY_OR = "|"
    BINARY_CARET = "^"
    BINARY_EQUAL = "="
    BINARY_LESS = "<"
    BINARY_GREATER = ">"
    BINARY_DOLLAR = "$"
    BINARY_COMMA = ","
    BINARY_HASH = "#"
    BINARY_UNDERSCORE = "_"
    BINARY_TILDE = "~"
    BINARY_BANG = "!"
    BINARY_QUESTION = "?"
    BINARY_AT = "@"
    BINARY_DOT = "."
    BINARY_ZERO_COLON = "0:"
    BINARY_ONE_COLON = "1:"
    BINARY_TWO_COLON = "2:"
    IN = "in"
    WITHIN = "within"
    LIKE = "like"
    BIN = "bin"
    SS = "ss"
    INSERT = "insert"
    WSUM = "wsum"
    WAVG = "wavg"
    DIV = "div"
    XEXP = "xexp"
    SETENV = "setenv"
    BINR = "binr"
    COV = "cov"
    COR = "cor"
    LSQ = "!"
    MMU = "$"

    # Named K101 aliases, verified against q 3.6 serialization.
    FLIP = "+:"
    NEG = "-:"
    FIRST = "*:"
    RECIPROCAL = "%:"
    LTIME = "%:"
    WHERE = "&:"
    REVERSE = "|:"
    NULL = "^:"
    GROUP = "=:"
    HCLOSE = ">:"
    STRING = "$:"
    COUNT = "#:"
    FLOOR = "_:"
    NOT = "~:"
    HDEL = "~:"
    KEY = "!:"
    INV = "!:"
    DISTINCT = "?:"
    TYPE = "@:"
    VALUE = ".:"
    GET = ".:"
    READ0 = "0::"
    READ1 = "1::"
