from enum import Enum


class Operator(Enum):
    """q unary primitives (IPC type 101); values are their q names.

    PLUS represents unary +:, not the binary + operator (type 102).
    Generic null is represented by None, separately from PROJECTION_NULL.
    """

    PLUS = "+:"
    MINUS = "-:"
    MULTIPLY = "*:"
    DIVIDE = "%:"
    AND = "&:"
    OR = "|:"
    CARET = "^:"
    EQUAL = "=:"
    LESS = "<:"
    GREATER = ">:"
    DOLLAR = "$:"
    COMMA = ",:"
    HASH = "#:"
    UNDERSCORE = "_:"
    TILDE = "~:"
    BANG = "!:"
    QUESTION = "?:"
    AT = "@:"
    DOT = ".:"
    ZERO_COLON = "0::"
    ONE_COLON = "1::"
    TWO_COLON = "2::"
    AVG = "avg"
    LAST = "last"
    SUM = "sum"
    PRD = "prd"
    MIN = "min"
    MAX = "max"
    EXIT = "exit"
    GETENV = "getenv"
    ABS = "abs"
    SQRT = "sqrt"
    LOG = "log"
    EXP = "exp"
    SIN = "sin"
    ASIN = "asin"
    COS = "cos"
    ACOS = "acos"
    TAN = "tan"
    ATAN = "atan"
    ENLIST = "enlist"
    VAR = "var"
    DEV = "dev"
    HOPEN = "hopen"
    PROJECTION_NULL = "::"
